import { PaymentMethod, SaleStatus } from '../enums';
import { SaleItem } from './sale-item.entity';

export class Sale {
  id: string;
  userId: string;
  customerId?: string;
  items: SaleItem[];
  subtotal: number; // in cents
  discount: number; // in cents
  total: number; // in cents
  paymentMethod?: PaymentMethod;
  status: SaleStatus;
  offlineId?: string; // UUID generated by frontend for offline sync
  syncedAt?: Date;
  createdAt: Date;
  updatedAt: Date;

  constructor(partial: Partial<Sale>) {
    Object.assign(this, partial);
    this.items = partial.items || [];
    this.discount = partial.discount || 0;
    this.status = partial.status || SaleStatus.PENDING;
    if (this.items.length > 0) {
      this.calculateTotals();
    }
  }

  // Business logic methods
  addItem(item: SaleItem): void {
    const existingItem = this.items.find(i => i.productId === item.productId);

    if (existingItem) {
      existingItem.updateQuantity(existingItem.quantity + item.quantity);
    } else {
      this.items.push(item);
    }

    this.calculateTotals();
  }

  removeItem(productId: string): void {
    this.items = this.items.filter(item => item.productId !== productId);
    this.calculateTotals();
  }

  updateItemQuantity(productId: string, newQuantity: number): void {
    const item = this.items.find(i => i.productId === productId);

    if (!item) {
      throw new Error('Item not found in sale');
    }

    if (newQuantity <= 0) {
      this.removeItem(productId);
    } else {
      item.updateQuantity(newQuantity);
      this.calculateTotals();
    }
  }

  applyDiscount(discountAmount: number): void {
    if (discountAmount < 0) {
      throw new Error('Discount cannot be negative');
    }

    if (discountAmount > this.subtotal) {
      throw new Error('Discount cannot be greater than subtotal');
    }

    this.discount = discountAmount;
    this.calculateTotals();
  }

  calculateTotals(): void {
    this.subtotal = this.items.reduce((sum, item) => sum + item.subtotal, 0);
    this.total = this.subtotal - this.discount;

    if (this.total < 0) {
      this.total = 0;
    }
  }

  finalize(paymentMethod: PaymentMethod): void {
    if (this.status !== SaleStatus.PENDING) {
      throw new Error('Only pending sales can be finalized');
    }

    if (this.items.length === 0) {
      throw new Error('Cannot finalize sale without items');
    }

    this.paymentMethod = paymentMethod;
    this.status = SaleStatus.COMPLETED;
    this.updatedAt = new Date();
  }

  cancel(): void {
    if (this.status === SaleStatus.CANCELLED) {
      throw new Error('Sale is already cancelled');
    }

    this.status = SaleStatus.CANCELLED;
    this.updatedAt = new Date();
  }

  isPending(): boolean {
    return this.status === SaleStatus.PENDING;
  }

  isCompleted(): boolean {
    return this.status === SaleStatus.COMPLETED;
  }

  isCancelled(): boolean {
    return this.status === SaleStatus.CANCELLED;
  }

  isOfflineSale(): boolean {
    return !!this.offlineId;
  }

  isSynced(): boolean {
    return !!this.syncedAt;
  }

  markAsSynced(): void {
    this.syncedAt = new Date();
  }

  getTotalInReais(): number {
    return this.total / 100;
  }

  getSubtotalInReais(): number {
    return this.subtotal / 100;
  }

  getDiscountInReais(): number {
    return this.discount / 100;
  }
}
